export type HistoricMoment = {
  id: string;
  section: "leisure" | "discovery";
  person: string;
  object: string;
  doing: string;
  title: string;
  later: string;
  pattern: string;
  evidence: "史料记载" | "本人回忆" | "轶事传说" | "典籍文本" | "诗中场景" | "唐人笔记" | "日记记载";
  sourceName: string;
  sourceUrl: string;
  imagePath: string;
  keywords: string[];
  sourceContext?: string;
};

export const historicMoments: HistoricMoment[] = [
  { id: "newton", section: "discovery", person: "艾萨克·牛顿", object: "一颗苹果", doing: "坐在花园里沉思", title: "《一次没有产出的发呆》", later: "皇家学会保存的斯图克利回忆录记载，牛顿在沉思时注意到苹果垂直落下，并追问它为何总朝向地面。这段故事不是“苹果砸中头”的版本。", pattern: "发呆 → 发现问题", evidence: "本人回忆", sourceName: "英国皇家学会：牛顿的苹果树", sourceUrl: "https://royalsociety.org/blog/2012/02/newtons-apple-tree/", imagePath: "/exhibits/ancient/newton.webp", keywords: ["发呆", "沉思", "为什么", "苹果", "观察", "走神", "抬头"] },
  { id: "penicillin", section: "discovery", person: "亚历山大·弗莱明", object: "一团霉菌", doing: "回到被霉菌污染的培养皿前", title: "《一个本来应该被扔掉的培养皿》", later: "1928 年，弗莱明注意到霉菌周围的葡萄球菌菌落被溶解，并进一步研究这种现象。青霉素后来由弗洛里、钱恩等人推动发展为治疗药物。", pattern: "污染 → 发现异常", evidence: "史料记载", sourceName: "诺贝尔奖：弗莱明自述与生平", sourceUrl: "https://www.nobelprize.org/prizes/medicine/1945/fleming/biographical/", imagePath: "/exhibits/ancient/penicillin.webp", keywords: ["失败", "污染", "霉菌", "发霉", "实验", "培养皿", "异常", "扔掉", "坏了"] },
  { id: "postit", section: "discovery", person: "斯宾塞·西尔弗与阿特·弗莱", object: "一瓶粘不牢的胶", doing: "做出一种粘性很弱、可以反复揭下的胶", title: "《一瓶“不好用”的胶水》", later: "西尔弗先做出了低粘性胶黏剂。多年后，弗莱把它用在可重复粘贴的书签上，发展成便利贴。", pattern: "失败 → 找到新用途", evidence: "史料记载", sourceName: "纽约现代艺术博物馆：Post-it 便签", sourceUrl: "https://www.moma.org/collection/works/4720", imagePath: "/exhibits/ancient/postit.webp", keywords: ["失败", "不好用", "胶水", "粘不住", "便利贴", "书签", "重复", "胶"] },
  { id: "pacemaker", section: "discovery", person: "威尔逊·格雷特巴奇", object: "一个拿错的电阻", doing: "焊接记录心音的电路", title: "《一个拿错的零件》", later: "他误拿了一个电阻，电路产生了有节律的脉冲。格雷特巴奇认出这与心跳节奏相似，随后参与研发可植入式心脏起搏器。", pattern: "犯错 → 发现新机制", evidence: "本人回忆", sourceName: "史密森尼 Lemelson 发明研究中心", sourceUrl: "https://invention.si.edu/invention-stories/innovative-lives-making-hearts-beat-wilson-greatbatch", imagePath: "/exhibits/ancient/pacemaker.webp", keywords: ["犯错", "拿错", "电阻", "零件", "电路", "节奏", "心跳", "焊接"] },
  { id: "velcro", section: "discovery", person: "乔治·德·梅斯特拉尔", object: "一颗粘在狗毛上的苍耳", doing: "散步回来清理衣服和狗毛", title: "《一颗粘在狗毛上的苍耳》", later: "他把苍耳放到显微镜下观察，发现细小钩状结构能挂住织物纤维，后来据此设计出钩环扣。", pattern: "闲逛 → 发现自然结构", evidence: "本人回忆", sourceName: "VELCRO® 品牌：发明故事", sourceUrl: "https://www.velcro.com/news-and-blog/2026/02/an-idea-that-stuck-how-george-de-mestral-invented-the-velcro-fastener/", imagePath: "/exhibits/ancient/velcro.webp", keywords: ["闲逛", "散步", "遛狗", "苍耳", "狗毛", "刺果", "自然", "显微镜", "粘住"] },
  { id: "graphene", section: "discovery", person: "安德烈·海姆与康斯坦丁·诺沃肖洛夫", object: "一片透明胶带和石墨", doing: "在星期五晚上的自由实验里反复剥离石墨", title: "《星期五晚上没人要求做的实验》", later: "两人用胶带从石墨中剥离出石墨烯，并因二维材料相关实验获得 2010 年诺贝尔物理学奖。海姆在访谈中也强调，后续仍做了大量严肃实验。", pattern: "玩耍 → 打开新的研究方向", evidence: "史料记载", sourceName: "诺贝尔奖：2010 年物理学奖速读与访谈", sourceUrl: "https://www.nobelprize.org/prizes/physics/2010/speedread/", imagePath: "/exhibits/ancient/graphene.webp", keywords: ["玩耍", "胶带", "透明胶", "石墨", "星期五", "实验", "材料", "剥离", "无聊"] },
  { id: "cn-confucius", section: "leisure", person: "孔子", object: "一段《韶》乐", doing: "在齐国听见《韶》乐，一时沉浸其中", title: "《一场听到忘记肉味的音乐》", later: "《论语·述而》记载孔子在齐国听《韶》乐，“三月不知肉味”，并感叹没想到音乐竟能美到这种地步。这里呈现的是典籍记下的专注聆听，不把“三月”解释成精确的九十天。", pattern: "沉浸 → 忘记日常", evidence: "典籍文本", sourceName: "《论语·述而》：子在齐闻韶", sourceUrl: "https://ctext.org/text.pl?if=gb&node=1264&remap=gb&show=parallel", imagePath: "/exhibits/ancient-chinese/confucius.webp", keywords: ["音乐", "听歌", "听曲", "韶乐", "忘记时间", "忘了吃", "肉味", "沉浸", "陶醉"] },
  { id: "cn-laozi", section: "leisure", person: "老子", object: "一座热闹的春台", doing: "看人群熙攘，自己安静地停在一旁", title: "《人群之外的停顿》", later: "《道德经》第二十章写“众人熙熙，如享太牢，如春登台，我独泊兮其未兆”。这幅画呈现的是文本中的第一人称意境，不当作可考证的老子亲历场景。", pattern: "热闹之外 → 安静自处", evidence: "典籍文本", sourceName: "《道德经》第二十章", sourceUrl: "https://ctext.org/wiki.pl?chapter=279815&if=en&remap=gb", imagePath: "/exhibits/ancient-chinese/laozi.webp", keywords: ["热闹", "春台", "人群", "安静", "旁观", "独处", "不合群", "淡泊", "停下来"] },
  { id: "cn-libai", section: "leisure", person: "李白", object: "月下一壶酒", doing: "独自饮酒，举杯邀明月与影子作伴", title: "《给月亮添一副酒杯》", later: "《月下独酌》写花间独饮、举杯邀月、与影成三人的想象。它没有要完成的目标，只把一个人的夜晚写成了有人相伴的时刻。", pattern: "独处 → 与月影共饮", evidence: "诗中场景", sourceName: "《全唐诗》卷一八二：月下独酌四首·其一", sourceUrl: "https://zh.wikisource.org/zh-hans/月下独酌_(花间一壶酒)", imagePath: "/exhibits/ancient-chinese/libai.webp", keywords: ["月亮", "月下", "影子", "独酌", "喝酒", "饮酒", "夜晚", "独自", "一个人", "邀月"] },
  { id: "cn-sushi", section: "leisure", person: "苏轼", object: "一场穿林的春雨", doing: "雨具先被同行带走，仍拄杖慢慢走过沙湖道", title: "《一场雨里的慢行》", later: "《定风波》小序记下沙湖道中遇雨，同行都很狼狈，苏轼却说“余独不觉”；词里又写“何妨吟啸且徐行”。这是一次途中遇雨和一首词，不是发明故事。", pattern: "遇雨 → 仍然徐行", evidence: "诗中场景", sourceName: "苏轼《定风波·莫听穿林打叶声》", sourceUrl: "https://zh.wikisource.org/zh-hans/定风波_(莫听穿林打叶声)", imagePath: "/exhibits/ancient-chinese/sushi.webp", keywords: ["下雨", "风雨", "雨天", "走路", "慢走", "散步", "竹杖", "芒鞋", "狼狈", "放晴"] },
  { id: "cn-taizong", section: "leisure", person: "唐太宗李世民", object: "一只漂亮的鹞", doing: "私下把鹞架在手臂上赏玩，见魏征来便藏进怀里", title: "《怀里藏着一只鹞》", later: "唐人刘餗《隋唐嘉话》记载，太宗得到一只出众的鹞，私下赏玩；魏征来奏事并谈起古代帝王逸乐，鹞最终死在太宗怀中。这是一则唐人笔记中的轶事，留下了帝王片刻玩心与职责相遇的画面。", pattern: "片刻玩心 → 遇见职责", evidence: "唐人笔记", sourceName: "刘餗《隋唐嘉话》：太宗得鹞", sourceUrl: "https://zh.wikisource.org/zh-hans/隋唐嘉话", imagePath: "/exhibits/ancient-chinese/taizong.webp", keywords: ["放松", "玩耍", "鸟", "鹰", "鹞", "怀里", "魏征", "偷闲", "宠物"] },
  { id: "cn-hushi", section: "leisure", person: "胡适", object: "一场课后牌局", doing: "暑期学校上完化学课后和同学打牌", title: "《七月六日，化学课之后打牌》", later: "中央研究院数字典藏所引胡适 1911 年 7 月 6 日日记：上午上化学课，之后记了“打牌”。资料未注明具体牌种，也不支持“整天打牌”的说法。", pattern: "课后消遣 → 被日记留下", evidence: "日记记载", sourceName: "中央研究院数字典藏：翻找档案中的故事", sourceUrl: "https://digiarch.sinica.edu.tw/content/subject/resource_content.jsp?oid=16777729&queryType=qc", imagePath: "/exhibits/ancient-chinese/hushi.webp", keywords: ["打牌", "上课", "课后", "日记", "消遣", "摸鱼", "娱乐", "闲暇"] },
  { id: "cn-taoyuanming", section: "leisure", person: "陶渊明", object: "篱边几朵菊", doing: "采菊时望见南山", title: "《采菊的下午》", later: "《饮酒》写“采菊东篱下，悠然见南山”。这是一种慢下来的诗中场景，不需要为它安排后来的成果。", pattern: "采菊 → 悠然自处", evidence: "诗中场景", sourceName: "陶渊明《饮酒二十首》", sourceUrl: "https://zh.wikisource.org/zh-hans/飲酒二十首", imagePath: "/exhibits/ancient-new/leisure/taoyuanming.webp", keywords: ["花", "菊花", "采菊", "田园", "山", "发呆", "下午", "闲坐"] },
  { id: "cn-baijuyi", section: "leisure", person: "白居易", object: "炉边一壶新酒", doing: "天冷时邀朋友来喝一杯", title: "《要不要来喝一杯？》", later: "《问刘十九》写下炉边新酒和一场即将到来的雪。诗里是邀请，并没有交代朋友最终是否赴约。", pattern: "小酌 → 等朋友来", evidence: "诗中场景", sourceName: "白居易《问刘十九》", sourceUrl: "https://zh.wikisource.org/zh/問劉十九", imagePath: "/exhibits/ancient-new/leisure/baijuyi.webp", keywords: ["酒", "喝酒", "朋友", "邀约", "下雪", "寒冷", "炉火", "聚会"] },
  { id: "cn-luyou", section: "leisure", person: "陆游", object: "一只小狸奴", doing: "与家里的猫相处", title: "《把猫迎进书房》", later: "陆游在《赠猫》中写“裹盐迎得小狸奴，尽护山房万卷书”。这里收藏的是养猫和写猫的日常乐趣。", pattern: "养猫 → 共享闲暇", evidence: "诗中场景", sourceName: "陆游《赠猫》", sourceUrl: "https://ctext.org/wiki.pl?chapter=953849&if=en&remap=gb", imagePath: "/exhibits/ancient-new/leisure/luyou.webp", keywords: ["猫", "宠物", "撸猫", "书房", "小狸奴", "陪伴", "休息"] },
  { id: "cn-liqingzhao", section: "leisure", person: "李清照", object: "一局打马", doing: "与朋友玩传统棋戏", title: "《词人也爱玩游戏》", later: "李清照写过《打马图序》，谈到自己喜爱“打马”这类棋戏。它不是现代麻将。", pattern: "游戏 → 认真玩耍", evidence: "典籍文本", sourceName: "李清照《打马图序》", sourceUrl: "https://zh.wikisource.org/zh-hans/打馬圖序_(李清照)", imagePath: "/exhibits/ancient-new/leisure/liqingzhao.webp", keywords: ["打马", "棋", "桌游", "游戏", "娱乐", "朋友", "玩耍"] },
  { id: "leisure-darwin", section: "leisure", person: "查尔斯·达尔文", object: "一盘双陆棋", doing: "饭后与妻子艾玛下棋", title: "《晚饭后的两局棋》", later: "儿子写的传记记下达尔文饭后与妻子玩双陆棋的习惯。它是家中的消遣，不必牵连到任何科学发现。", pattern: "饭后下棋 → 日常休息", evidence: "史料记载", sourceName: "Darwin Online：达尔文传记", sourceUrl: "https://darwin-online.org.uk/content/contentblock?basepage=1&hitpage=45&itemID=F1461&viewtype=text", imagePath: "/exhibits/ancient-new/leisure/darwin.webp", keywords: ["下棋", "棋", "饭后", "夫妻", "游戏", "桌游", "休息"] },
  { id: "leisure-einstein", section: "leisure", person: "阿尔伯特·爱因斯坦", object: "湖上的一只小帆船", doing: "在普林斯顿附近的湖上航行", title: "《湖上无须解方程》", later: "爱因斯坦喜欢驾帆船，也喜欢音乐。这里是他的休闲生活，不给航行附会一条科学定律。", pattern: "划船 → 给思绪放风", evidence: "史料记载", sourceName: "普林斯顿历史学会：爱因斯坦", sourceUrl: "https://princetonhistory.org/research/historic-princeton/albert-einstein/", imagePath: "/exhibits/ancient-new/leisure/einstein.webp", keywords: ["帆船", "湖", "划船", "航行", "水", "音乐", "休息", "散心"] },
  { id: "leisure-curie", section: "leisure", person: "玛丽·居里", object: "两辆自行车", doing: "与皮埃尔一起骑车远行", title: "《把一天交给车轮》", later: "玛丽与皮埃尔·居里曾一起骑车旅行。骑行也是他们共同生活的一部分，而非一次实验。", pattern: "骑车 → 一起远行", evidence: "史料记载", sourceName: "诺贝尔奖官网：居里夫妇", sourceUrl: "https://www.nobelprize.org/prizes/themes/marie-and-pierre-curie-and-the-discovery-of-polonium-and-radium/", imagePath: "/exhibits/ancient-new/leisure/curie.webp", keywords: ["骑车", "自行车", "旅行", "远行", "伴侣", "郊游", "散心"] },
  { id: "leisure-frida", section: "leisure", person: "弗里达·卡罗", object: "蓝房子的花园", doing: "在花园里与朋友和动物相伴", title: "《花园里的一段时间》", later: "弗里达故居的资料记下她与朋友、动物在蓝房子里的生活。此处只呈现平常的陪伴，不把每一次散步解释成画作的起点。", pattern: "花园 → 陪伴自己", evidence: "史料记载", sourceName: "弗里达·卡罗博物馆", sourceUrl: "https://www.museofridakahlo.org.mx/frida/?lang=en", imagePath: "/exhibits/ancient-new/leisure/frida.webp", keywords: ["花园", "宠物", "动物", "朋友", "散步", "植物", "陪伴"] },
  { id: "leisure-churchill", section: "leisure", person: "温斯顿·丘吉尔", object: "一幅未画完的风景", doing: "暂时放下公务去画画", title: "《今天先画一会儿》", later: "绘画是丘吉尔长期保持的私人爱好，也帮助他从繁忙的政治生活中抽身。", pattern: "画画 → 暂离事务", evidence: "史料记载", sourceName: "丘吉尔档案馆：绘画", sourceUrl: "https://www.churchillarchive.com/topic-in-focus", imagePath: "/exhibits/ancient-new/leisure/churchill.webp", keywords: ["画画", "绘画", "风景", "涂鸦", "爱好", "公务", "放松"] },
  { id: "leisure-truman", section: "leisure", person: "哈里·杜鲁门", object: "一桌扑克牌", doing: "与朋友定期打扑克", title: "《总统也有牌局》", later: "美国国家档案馆记载了杜鲁门和朋友们的牌局。即使身居高位，也可以有一段单纯的社交和放松时间。", pattern: "牌局 → 社交休息", evidence: "史料记载", sourceName: "美国国家档案馆：杜鲁门与扑克", sourceUrl: "https://www.archives.gov/publications/prologue/2003/spring/truman-poker.html", imagePath: "/exhibits/ancient-new/leisure/truman.webp", keywords: ["打牌", "扑克牌", "朋友", "牌局", "社交", "放松", "游戏"] },
  { id: "leisure-austen", section: "leisure", person: "简·奥斯汀", object: "一场乡间舞会", doing: "跳舞、聊天、认识朋友", title: "《舞会上的一个晚上》", later: "奥斯汀的书信留下了她参加舞会的经历。舞会可以只是跳舞与交谈，不必预告下一部小说。", pattern: "跳舞 → 与人相聚", evidence: "史料记载", sourceName: "简·奥斯汀故居：书信与舞会", sourceUrl: "https://janeaustens.house/online-exhibition/six-winters-online/six-winters-scene-3/", imagePath: "/exhibits/ancient-new/leisure/austen.webp", keywords: ["跳舞", "舞会", "聊天", "朋友", "社交", "聚会", "晚上"] },
  { id: "leisure-twain", section: "leisure", person: "马克·吐温", object: "一张台球桌", doing: "和朋友打台球到深夜", title: "《再打一局台球》", later: "马克·吐温故居介绍了他在台球室与朋友消磨晚间时光的习惯。", pattern: "打台球 → 忘记时间", evidence: "史料记载", sourceName: "马克·吐温故居：台球室", sourceUrl: "https://marktwainhouse.org/rooms/", imagePath: "/exhibits/ancient-new/leisure/twain.webp", keywords: ["台球", "朋友", "深夜", "游戏", "消磨", "忘记时间"] },
  { id: "leisure-franklin", section: "leisure", person: "本杰明·富兰克林", object: "一盘棋", doing: "下棋下到占用了学习语言的时间", title: "《棋盘比功课有趣》", later: "富兰克林在自传中谈到自己下棋的爱好，以及它占用学习语言时间的问题。连善于自我安排的人也会被游戏吸引。", pattern: "下棋 → 暂忘计划", evidence: "本人回忆", sourceName: "富兰克林《自传》", sourceUrl: "https://tile.loc.gov/storage-services/public/gdcmassbookdig/autobiographyofb02fran/autobiographyofb02fran.pdf", imagePath: "/exhibits/ancient-new/leisure/franklin.webp", keywords: ["棋", "下棋", "功课", "拖延", "学习", "游戏", "分心"] },
  { id: "leisure-john-quincy-adams", section: "leisure", person: "约翰·昆西·亚当斯", object: "一个热闹的夜晚", doing: "年轻时打牌、跳舞、唱歌", title: "《玩完以后也会自责》", later: "马萨诸塞历史学会整理的日记显示，他在学习法律的时期参加牌局、舞会等活动，有时也为这些消遣带来的分心而自责。", pattern: "玩耍 → 偶尔内疚", evidence: "日记记载", sourceName: "马萨诸塞历史学会：亚当斯日记", sourceUrl: "https://www.masshist.org/publications/adams-papers/index.php/view/ADMS-03-01-01-0008", imagePath: "/exhibits/ancient-new/leisure/john-quincy-adams.webp", keywords: ["打牌", "跳舞", "唱歌", "自责", "内疚", "拖延", "分心", "晚上"] },
  { id: "discovery-wangxizhi", section: "discovery", person: "王羲之", object: "兰亭的一场春游", doing: "与友人临水饮酒、作诗", title: "《曲水边写下的序》", later: "兰亭聚会中，众人临水饮酒、作诗，王羲之随后为诗集写序。它来自一次真实的文会，不是随手涂鸦便成名作。", pattern: "聚会 → 书法与文章", evidence: "典籍文本", sourceName: "王羲之《兰亭集序》", sourceUrl: "https://zh.wikisource.org/zh-hans/蘭亭修褉詩集序", imagePath: "/exhibits/ancient-new/discovery/wangxizhi.webp", keywords: ["春游", "聚会", "朋友", "喝酒", "饮酒", "书法", "写字", "流水"] },
  { id: "discovery-zhangxu", section: "discovery", person: "张旭", object: "一场剑舞", doing: "看公孙大娘的剑舞入迷", title: "《从舞步看见笔势》", later: "杜甫诗序转述张旭观看公孙大娘舞剑后，草书受到启发的故事。这里依据后人的文字记录，不还原成确定无疑的亲历镜头。", pattern: "观舞 → 启发草书", evidence: "典籍文本", sourceName: "杜甫《观公孙大娘弟子舞剑器行》序", sourceUrl: "https://www.gushiwen.cn/shiwenv_ab7f5336bda5.aspx", imagePath: "/exhibits/ancient-new/discovery/zhangxu.webp", keywords: ["跳舞", "剑舞", "舞蹈", "书法", "草书", "动作", "节奏", "观看"] },
  { id: "discovery-zhangdai", section: "discovery", person: "张岱", object: "深夜湖上的雪", doing: "乘船去湖心亭看雪", title: "《夜里专程去看一场雪》", later: "张岱在《湖心亭看雪》中记下雪夜泛舟西湖的经历。这段无明确用途的出行，后来成为一篇短文。", pattern: "看雪 → 写下见闻", evidence: "本人回忆", sourceName: "张岱《湖心亭看雪》", sourceUrl: "https://zh.wikisource.org/zh/湖心亭看雪", imagePath: "/exhibits/ancient-new/discovery/zhangdai.webp", keywords: ["下雪", "看雪", "夜晚", "深夜", "湖", "划船", "旅行", "风景"] },
  { id: "discovery-mary-shelley", section: "discovery", person: "玛丽·雪莱", object: "一场写鬼故事的约定", doing: "夜里想着还没写出的故事", title: "《鬼故事之夜之后》", later: "玛丽·雪莱在 1831 年序言中回忆，聚会中的写作约定与后来脑海里的画面，逐步成为《弗兰肯斯坦》的起点。这是作者多年后的回望。", pattern: "聚会 → 小说构想", evidence: "本人回忆", sourceName: "玛丽·雪莱《弗兰肯斯坦》1831 年序言", sourceUrl: "https://en.wikisource.org/wiki/Page:Frankenstein,_or_the_Modern_Prometheus_(Revised_Edition,_1831).djvu/17", imagePath: "/exhibits/ancient-new/discovery/mary-shelley.webp", keywords: ["做梦", "梦", "失眠", "夜晚", "鬼故事", "聚会", "小说", "想象"] },
  { id: "discovery-tolkien", section: "discovery", person: "J. R. R. 托尔金", object: "试卷上的空白页", doing: "批改试卷时随手写下一句话", title: "《空白纸上的霍比特人》", later: "托尔金回忆，批改试卷时看到空白页，写下关于霍比特人的一句话；故事经过多年构思，成为《霍比特人》。", pattern: "空白页 → 故事开端", evidence: "本人回忆", sourceName: "托尔金遗产机构：《霍比特人》缘起", sourceUrl: "https://www.tolkienestate.com/writing/john-d-rateliff-the-hobbit/", imagePath: "/exhibits/ancient-new/discovery/tolkien.webp", keywords: ["批改", "试卷", "空白", "随手写", "写字", "故事", "小说", "工作"] },
  { id: "discovery-lewis-carroll", section: "discovery", person: "刘易斯·卡罗尔", object: "一趟划船", doing: "给孩子们即兴讲故事", title: "《船上开始的一段冒险》", later: "1862 年的划船出游中，卡罗尔为孩子们讲述爱丽丝的故事，后来写成手稿，并发展为《爱丽丝漫游奇境》。", pattern: "讲故事 → 小说诞生", evidence: "史料记载", sourceName: "大英图书馆：爱丽丝手稿", sourceUrl: "https://searcharchives.bl.uk/catalog/040-001611723", imagePath: "/exhibits/ancient-new/discovery/lewis-carroll.webp", keywords: ["划船", "孩子", "讲故事", "即兴", "河", "旅行", "小说"] },
  { id: "discovery-beatrix-potter", section: "discovery", person: "毕翠克丝·波特", object: "给孩子的一封信", doing: "画兔子写信安慰生病的孩子", title: "《一封信里的彼得兔》", later: "波特写给孩子的插画信里出现兔子故事，之后经过整理和出版，成为《彼得兔》。", pattern: "写信 → 童书故事", evidence: "史料记载", sourceName: "维多利亚与艾尔伯特博物馆：彼得兔", sourceUrl: "https://www.vam.ac.uk/articles/peter-rabbit-the-tale-of-the-tale", imagePath: "/exhibits/ancient-new/discovery/beatrix-potter.webp", keywords: ["写信", "兔子", "画画", "孩子", "生病", "童书", "安慰", "插画"] },
  { id: "discovery-mccartney", section: "discovery", person: "保罗·麦卡特尼", object: "梦里的一段旋律", doing: "醒来后记下听到的旋律", title: "《醒来先记住它》", later: "麦卡特尼回忆《Yesterday》的旋律最初来自梦中；词曲仍经过后续打磨。", pattern: "做梦 → 写成歌曲", evidence: "本人回忆", sourceName: "披头士官网：Yesterday", sourceUrl: "https://www.thebeatles.com/yesterday-0", imagePath: "/exhibits/ancient-new/discovery/mccartney.webp", keywords: ["梦", "做梦", "睡觉", "醒来", "旋律", "音乐", "歌曲", "钢琴"] },
  { id: "discovery-dali", section: "discovery", person: "萨尔瓦多·达利", object: "一块变软的奶酪", doing: "想到画中那些融化的钟", title: "《软下来的时间》", later: "达利事后把卡门贝尔奶酪与《记忆的永恒》中的软钟联系起来。现代艺术博物馆指出其创作过程的部分细节有争议，应视为艺术家的回忆说法。", pattern: "日常物象 → 超现实绘画", evidence: "本人回忆", sourceName: "纽约现代艺术博物馆：达利与软钟", sourceUrl: "https://www.moma.org/magazine/articles/1386", imagePath: "/exhibits/ancient-new/discovery/dali.webp", keywords: ["奶酪", "融化", "钟表", "时间", "绘画", "画画", "发呆", "想象"], sourceContext: "奶酪与画作的联系来自艺术家事后自述，具体创作时间线有争议。" },
  { id: "discovery-calder", section: "discovery", person: "亚历山大·考尔德", object: "墙上的彩色方块", doing: "参观蒙德里安的工作室", title: "《如果让画动起来》", later: "考尔德参观蒙德里安工作室时，被彩色几何形吸引，后来不断探索运动与雕塑的关系，发展出活动雕塑。", pattern: "参观 → 想象运动", evidence: "史料记载", sourceName: "考尔德基金会：1930 年工作室访问", sourceUrl: "https://calder.org/works/oil-painting/untitled-1930-17/", imagePath: "/exhibits/ancient-new/discovery/calder.webp", keywords: ["参观", "画", "彩色", "方块", "移动", "运动", "雕塑", "工作室"] },
  { id: "discovery-john-cage", section: "discovery", person: "约翰·凯奇", object: "放不下打击乐的舞台", doing: "试着让钢琴发出别的声音", title: "《一架钢琴变成了乐队》", later: "凯奇为舞蹈演出写音乐时，场地容不下打击乐器，于是尝试在琴弦间放入物件，发展出预制钢琴。", pattern: "场地限制 → 新的声音", evidence: "本人回忆", sourceName: "约翰·凯奇：自传陈述", sourceUrl: "https://johncage.org/cage-autobiographical-statement", imagePath: "/exhibits/ancient-new/discovery/john-cage.webp", keywords: ["钢琴", "音乐", "声音", "限制", "舞蹈", "乐器", "实验", "演出"] },
  { id: "discovery-ruth-handler", section: "discovery", person: "露丝·汉德勒", object: "女儿手中的纸娃娃", doing: "看女儿替娃娃编排成人生活", title: "《看孩子怎么玩》", later: "汉德勒从女儿玩纸娃娃的方式中看到成人形象玩偶的需求。芭比娃娃还经过后续设计与商业开发，并非一次观察就直接定型。", pattern: "观察玩耍 → 玩具构想", evidence: "史料记载", sourceName: "美国国会图书馆：芭比诞生", sourceUrl: "https://guides.loc.gov/this-month-in-business-history/march/ruth-handler-introduces-barbie", imagePath: "/exhibits/ancient-new/discovery/ruth-handler.webp", keywords: ["孩子", "娃娃", "玩具", "纸", "观察", "玩耍", "女儿", "游戏"] },
  { id: "discovery-montaigne", section: "discovery", person: "米歇尔·德·蒙田", object: "一只正在玩耍的猫", doing: "与猫玩时想谁在逗谁", title: "《到底是谁陪谁玩？》", later: "蒙田在《随笔集》中从与猫玩耍反问人的自我中心视角。这里的“后来”是一段思想表达，不是一件发明。", pattern: "玩猫 → 哲学追问", evidence: "典籍文本", sourceName: "蒙田《随笔集》", sourceUrl: "https://www.gutenberg.org/files/3600/3600-h/3600-h", imagePath: "/exhibits/ancient-new/discovery/montaigne.webp", keywords: ["猫", "宠物", "玩耍", "陪伴", "思考", "哲学", "发问", "动物"] },
  { id: "discovery-basho", section: "discovery", person: "松尾芭蕉", object: "古池里的一声水响", doing: "留意青蛙入水的细小声响", title: "《古池里的一声水响》", later: "古池、青蛙与水声成为芭蕉著名俳句的诗中场景。它不是可逐帧复原的创作现场。", pattern: "细小声响 → 一首俳句", evidence: "诗中场景", sourceName: "福田美术馆馆藏：芭蕉古池俳句", sourceUrl: "https://artsandculture.google.com/asset/「ふる池や」発句短冊・極書-松尾芭蕉、沢露川/0QEs07xS5Heiow", imagePath: "/exhibits/ancient-new/discovery/basho.webp", keywords: ["青蛙", "池塘", "水声", "声音", "自然", "诗", "发呆", "观察"], sourceContext: "画面依据俳句意象创作，不声称能复原芭蕉写作时亲眼所见。" },
];

const ideaClues: Record<string, { pattern: RegExp; connection: string }> = {
  newton: { pattern: /发呆|走神|沉思|为什么|盯着|看着|好奇|掉下来|落下|坠落|重力/, connection: "相似处在于停下来观察一件平常的事。" },
  penicillin: { pattern: /凝住|变化|变了|变质|发霉|坏掉|异常|没想到|不对劲|污染|残留|忘了|忘记/, connection: "相似处在于注意到原本容易被忽略的变化。" },
  postit: { pattern: /失败|不好用|没用上|不管用|粘|贴|被丢弃|扔掉|留下|收着|保存/, connection: "相似处在于没有立刻丢掉暂时不好用的东西。" },
  pacemaker: { pattern: /拿错|弄错|犯错|按错|搞错|误打误撞|手滑|错位|节奏|心跳/, connection: "相似处在于从偏离预期的动作里发现另一种可能。" },
  velcro: { pattern: /闲逛|散步|遛狗|路上|衣服|植物|花草|树叶|落叶|狗毛|小刺/, connection: "相似处在于从日常路过的事物里发现值得细看的结构。" },
  graphene: { pattern: /玩耍|试着|试试|随手|胡乱|折腾|剥|撕|胶带|重复试/, connection: "相似处在于给没有明确目标的尝试留出一点时间。" },
  "cn-confucius": { pattern: /音乐|听歌|听曲|韶乐|忘记时间|忘了吃|沉浸|陶醉/, connection: "相似处在于一段体验吸引了全部注意力。" },
  "cn-laozi": { pattern: /热闹|春台|人群|安静|旁观|独处|不合群|淡泊|停下来/, connection: "相似处在于在喧闹之外，留意自己的节奏。" },
  "cn-libai": { pattern: /月亮|月下|影子|独酌|喝酒|饮酒|夜晚|独自|一个人|邀月/, connection: "相似处在于把独处的一刻变成自己的想象空间。" },
  "cn-sushi": { pattern: /下雨|风雨|雨天|走路|慢走|散步|竹杖|芒鞋|狼狈|放晴/, connection: "相似处在于事情没按计划发生，仍愿意慢下来感受它。" },
  "cn-taizong": { pattern: /放松|玩耍|鸟|鹰|鹞|魏征|偷闲|宠物/, connection: "相似处在于一段私人消遣与眼前责任碰在了一起。" },
  "cn-hushi": { pattern: /打牌|上课|课后|日记|消遣|摸鱼|娱乐|闲暇/, connection: "相似处在于普通的消遣也值得如实记录下来。" },
};

export function findHistoricConnections(text: string) {
  const query = text.toLowerCase().trim();
  if (!query) return [];
  return historicMoments.map((moment) => {
    const words = moment.keywords.filter((keyword) => query.includes(keyword.toLowerCase())).sort((a, b) => b.length - a.length);
    const idea = ideaClues[moment.id];
    const hasIdea = idea?.pattern.test(query) ?? false;
    const score = words.reduce((sum, word) => sum + 3 + word.length / 2, 0) + (hasIdea ? 2 : 0);
    const lead = words[0] ? `你写下了「${words[0]}」；` : "";
    return { moment, score, resonance: `${lead}${idea?.connection ?? (moment.section === "leisure" ? "名人也有一段只属于生活的时间。" : "一件小事也可能成为继续留意和追问的起点。")}` };
  }).filter(({ score }) => score > 0).sort((a, b) => b.score - a.score).slice(0, 3);
}
